export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const CREATE_BLOG = 'CREATE_BLOG';
export const USER_COLLECTIONS_FETCHED = 'USER_COLLECTIONS_FETCHED';
export const FETCH_BLOG = 'FETCH_BLOG';
export const COMMENTS_FETCHED = 'COMMENTS_FETCHED';
export const CREATE_COMMENT ='CREATE_COMMENT';
export const RELATED_FETCHED = 'RELATED_FETCHED';
export const FETCH_PRIMARY_CATEGORY = 'FETCH_PRIMARY_CATEGORY';
export const LATEST_FETCHED ='LATEST_FETCHED';
export const CATEGORY_HOMEPAGE_UI_A = 'CATEGORY_HOMEPAGE_UI_A';
export const CATEGORY_HOMEPAGE_UI_B = 'CATEGORY_HOMEPAGE_UI_B';
export const CATEGORY_HOMEPAGE_UI_C = 'CATEGORY_HOMEPAGE_UI_C';
export const ALL_FETCHED = 'ALL_FETCHED';
export const CATEGORY_COLLECTION_FETCHED = 'CATEGORY_COLLECTION_FETCHED';